[[plugins]]
repo = 'Shougo/dein.vim'

# --------------------------------------------
#  ファイラー
# --------------------------------------------
    [[plugins]]
    repo = 'scrooloose/nerdtree'
    hook_add = '''
        nnoremap <silent><C-f> :NERDTreeToggle<CR>
        " ブックマークを初期表示
        let g:NERDTreeShowBookmarks=1
        " autocmd vimenter * NERDTree
        " Vim起動時にNERDTreeを表示
    '''
# --------------------------------------------
#  アイコン
# --------------------------------------------

    [[plugins]]
    repo = 'ryanoasis/vim-devicons'
    hook_add = '''
        let g:webdevicons_enable_nerdtree=1
    '''

# --------------------------------------------
#  シンタックスハイライト
# --------------------------------------------

    [[plugins]]
    repo = 'sheerun/vim-polyglot'

# --------------------------------------------
#  マークダウンプレビュー
# --------------------------------------------

    [[plugins]]
    repo = 'skanehira/preview-markdown.vim'
    hook_add = '''
        let g:preview_markdown_parser='glow'
        let g:preview_markdown_vertical=1
        let g:preview_markdown_auto_update=1
    '''
# --------------------------------------------
#  Gitの操作
# --------------------------------------------
    [[plugins]]
    repo= 'airblade/vim-gitgutter'
    [[plugins]]
    repo = 'tpope/vim-fugitive'
